line-length = 99
target-version = "py313"

[lint]
select = [
    "A",    # flake8-builtins
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "C90",  # mccabe (check max complexity)
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "ISC",  # flake8-implicit-str-concat
    "N",    # pep8-naming
    "PTH",  # flake8-use-pathlib
    "Q",    # flake8-quotes
    "S",    # flake8-bandit
    "T20",  # flake8-print
]
ignore = [
    "N818",     # error-suffix-on-exception-name
    "N802",     # invalid-function-name
    "S104",     # hardcoded-bind-all-interfaces
]

[lint.isort]
known-first-party = ["src"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]    # unused imports
"tests/*" = ["S101"]        # use of assert
