name: Lint and Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Install the code linting and formatting tool Ruff
        run: |
          pipx install ruff

      - name: Lint code with Ruff
        run: |
          ruff check --output-format=github

      - name: Check code formatting with Ruff
        run: |
          ruff format --diff
        continue-on-error: true

  publish:
    needs: check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/simple-http:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/simple-http:${{ github.sha }}
